const pages=['overview','portfolio','markets','agents','risk','analytics','system-plan','settings'];
const labels={'system-plan':'System Plan'};let state=null;
const nav=document.querySelector('#nav');pages.forEach(p=>{const a=document.createElement('a');a.href=`#${p}`;a.textContent=labels[p]||p[0].toUpperCase()+p.slice(1);nav.append(a)});
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty=t=>`<div class="empty">${esc(t)}</div>`;
function cards(items){return `<div class="grid">${items.map(x=>`<article class="card ${x.wide?'wide':''}"><label>${esc(x.label)}</label><strong>${esc(x.value)}</strong><small>${esc(x.note)}</small></article>`).join('')}</div>`}
function render(){const page=pages.includes(location.hash.slice(1))?location.hash.slice(1):'overview';document.querySelector('#page-title').textContent=labels[page]||page[0].toUpperCase()+page.slice(1);[...nav.children].forEach(a=>a.classList.toggle('active',a.hash===`#${page}`));const v=document.querySelector('#view');if(page==='system-plan'){v.innerHTML='<iframe title="4 Sigma System Plan" src="system-plan.html"></iframe>';return}if(!state){v.innerHTML=empty('Connecting to the 4 Sigma backend…');return}const run=state.run;
 if(page==='overview')v.innerHTML=`<div class="hero"><h2>Governed research. Deterministic risk.</h2><p>Operational view of the point-in-time research, governance, portfolio-risk and paper-execution pipeline.</p></div>${cards([{label:'SYSTEM',value:state.system.status,note:state.system.mode},{label:'REGISTERED AGENTS',value:state.agents.length,note:'Versioned runtime specifications'},{label:'ACTIVE RUN',value:run?'Loaded':'None',note:run?'Completed run data':'Start or load a backtest'},{label:'RISK AUTHORITY',value:'Deterministic',note:'Models cannot override vetoes'}])}`;
 else if(page==='agents')v.innerHTML=`<div class="hero"><h2>Agent registry</h2><p>These entries come directly from the Python agent registry.</p></div><table><thead><tr><th>AGENT</th><th>VERSION</th><th>ROLE / OUTPUT</th><th>STATE</th></tr></thead><tbody>${state.agents.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.version)}</td><td>${esc(a.output)}</td><td><span class="pill">Registered</span></td></tr>`).join('')}</tbody></table>`;
 else if(page==='settings')v.innerHTML=`<div class="hero"><h2>Runtime settings</h2><p>Read-only operational configuration. Secrets are never returned to the browser.</p></div>${cards([{label:'NEWS MODEL',value:state.settings.news_model,note:'Environment override supported'},{label:'DECISION MODEL',value:state.settings.decision_model,note:'Environment override supported'},{label:'API KEY',value:state.settings.api_key_configured?'Configured':'Not configured',note:'Secret value remains server-side'},{label:'EXECUTION',value:'Paper only',note:'No live brokerage authority'}])}`;
 else if(!run)v.innerHTML=`<div class="hero"><h2>${document.querySelector('#page-title').textContent}</h2><p>This view is connected to the backend and will populate only from a completed, audited run.</p></div>${empty('No completed run is loaded. No values have been fabricated.')}`;
 else v.innerHTML=empty('Run visualization contract is ready; no persisted run was supplied.');}
async function load(){try{const r=await fetch('/api/dashboard',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);state=await r.json();document.querySelector('#backend-status').textContent='Connected';render()}catch(e){state={system:{status:'Frontend only',mode:'Start web.server for live data'},agents:[],run:null,settings:{news_model:'—',decision_model:'—',api_key_configured:false}};document.querySelector('#backend-status').textContent='Offline';render()}}
window.addEventListener('hashchange',render);document.querySelector('#refresh').addEventListener('click',load);load();
